/**
 * Feature catalog — hand-curated map of operator-facing pages and what they do.
 *
 * Two consumers:
 *   1. `get_current_screen_context` enriches its response with a `page` block
 *      so Henry knows what the user is currently looking at (not just the URL).
 *   2. `find_feature` lets Henry answer "where is X?" / "can I do X?" by
 *      searching this catalog.
 *
 * This is interim. Phase 2 replaces it with a `public.help_docs` corpus
 * generated by an operator-audience doc-writer agent (see kanban). When that
 * lands, `find_feature` switches to embedding search and this static list
 * is retired.
 *
 * Conventions:
 *   - `path` matches the dashboard route exactly (no trailing slash).
 *   - `summary` is one sentence describing what the operator does on this page.
 *   - `keywords` are alternate phrasings a user might say. Lowercase.
 *   - Only include pages an operator might ASK about. Skip purely transactional
 *     edit/new sub-pages unless they're a destination.
 */

export type FeatureEntry = {
  path: string;
  name: string;
  summary: string;
  keywords: string[];
};

export const FEATURE_CATALOG: FeatureEntry[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    summary: 'Daily snapshot — open jobs, pipeline, attention items, and revenue.',
    keywords: ['home', 'overview', 'today', 'snapshot'],
  },
  {
    path: '/business-health',
    name: 'Business Health',
    summary: 'Cash flow, AR, expenses, and bookkeeping reconciliation.',
    keywords: ['health', 'finances', 'cashflow', 'bank', 'reconcile', 'gst'],
  },
  {
    path: '/business-health/bank-import',
    name: 'Bank Import',
    summary: 'Upload bank statements (CSV/PDF) to import transactions.',
    keywords: ['bank', 'statement', 'import', 'transactions'],
  },
  {
    path: '/business-health/bank-review',
    name: 'Bank Review',
    summary: 'Match imported bank transactions to expenses or invoices.',
    keywords: ['reconcile', 'match', 'bank', 'review'],
  },
  {
    path: '/contacts',
    name: 'Contacts',
    summary: 'Customers, vendors, subs, agents, inspectors, and referral partners.',
    keywords: ['customer', 'vendor', 'sub', 'subcontractor', 'agent', 'inspector', 'address book'],
  },
  {
    path: '/projects',
    name: 'Projects',
    summary:
      'Multi-week renovation projects with phases, budgets, change orders, and the customer portal.',
    keywords: ['project', 'reno', 'renovation', 'job', 'work'],
  },
  {
    path: '/jobs',
    name: 'Jobs',
    summary: 'Single-visit jobs (pressure washing / day-of work) with scheduling and status.',
    keywords: ['job', 'visit', 'schedule', 'appointment'],
  },
  {
    path: '/calendar',
    name: 'Calendar',
    summary: 'Calendar view of scheduled work and team time.',
    keywords: ['calendar', 'schedule', 'agenda', 'when'],
  },
  {
    path: '/quotes',
    name: 'Quotes',
    summary: 'Create, send, and track customer quotes with assemblies and pricing.',
    keywords: ['quote', 'estimate', 'pricing', 'bid', 'proposal'],
  },
  {
    path: '/invoices',
    name: 'Invoices',
    summary: 'Create and send invoices and project draws; track payments via Stripe.',
    keywords: ['invoice', 'bill', 'payment', 'draw', 'stripe', 'collect'],
  },
  {
    path: '/expenses',
    name: 'Expenses',
    summary: 'Receipts, bills, recurring overheads, and per-card OCR auto-tagging.',
    keywords: ['expense', 'receipt', 'bill', 'overhead', 'cost', 'spending'],
  },
  {
    path: '/expenses/gst',
    name: 'GST Remittance',
    summary: 'Calculate and file GST/HST remittance with input tax credits.',
    keywords: ['gst', 'hst', 'tax', 'remittance', 'cra', 'itc'],
  },
  {
    path: '/inbox',
    name: 'Inbox',
    summary: 'Inbound emails, customer messages, and items needing operator attention.',
    keywords: ['email', 'message', 'inbox', 'inbound'],
  },
  {
    path: '/checklists',
    name: 'Checklists',
    summary: 'Reusable task checklists for jobs and projects.',
    keywords: ['checklist', 'tasks', 'template'],
  },
  {
    path: '/todos',
    name: 'Todos',
    summary: 'Personal task list — overdue, due-today, and upcoming.',
    keywords: ['todo', 'task', 'reminder', 'do', 'list'],
  },
  {
    path: '/import',
    name: 'Import',
    summary:
      'Bulk-import contacts, projects, invoices, and expenses from spreadsheets or other apps.',
    keywords: ['import', 'csv', 'migrate', 'bulk', 'upload', 'spreadsheet'],
  },
  {
    path: '/referrals',
    name: 'Refer & Earn',
    summary: 'Share your referral link, send invites by email or SMS, and track signups.',
    keywords: ['refer', 'referral', 'invite', 'reward', 'friend', 'rewards'],
  },
  {
    path: '/settings',
    name: 'Settings',
    summary: 'Hub for profile, billing, team, automations, and configuration.',
    keywords: ['settings', 'config', 'preferences'],
  },
  {
    path: '/settings/team',
    name: 'Team',
    summary: 'Add team members, set roles, and manage worker access.',
    keywords: ['team', 'members', 'workers', 'staff', 'roles', 'invite team'],
  },
  {
    path: '/settings/billing',
    name: 'Billing',
    summary: 'Subscription plan, payment method, and trial status.',
    keywords: ['subscription', 'plan', 'upgrade', 'billing', 'pay'],
  },
  {
    path: '/settings/profile',
    name: 'Business Profile',
    summary: 'Business name, logo, address, and customer-facing branding.',
    keywords: ['profile', 'logo', 'branding', 'business name', 'company'],
  },
  {
    path: '/settings/automations',
    name: 'Automations',
    summary: 'Configure follow-up sequences and reminders that send on their own.',
    keywords: ['automation', 'autoresponder', 'sequence', 'follow-up', 'drip'],
  },
  {
    path: '/settings/reminders',
    name: 'Reminders',
    summary: 'Notification preferences for SMS and email reminders.',
    keywords: ['reminder', 'notification', 'alert', 'sms', 'email'],
  },
  {
    path: '/settings/payment-sources',
    name: 'Payment Sources',
    summary: 'Label credit cards and accounts so receipts auto-tag to the right source.',
    keywords: ['payment source', 'card', 'credit card', 'account', 'tag'],
  },
  {
    path: '/settings/catalog',
    name: 'Service Catalog',
    summary: 'Reusable services and pricing used in quotes.',
    keywords: ['catalog', 'services', 'pricing', 'price list'],
  },
  {
    path: '/settings/cost-catalog',
    name: 'Cost Catalog',
    summary: 'Vendor cost benchmarks and material pricing for estimating.',
    keywords: ['cost', 'pricing', 'vendor', 'material', 'benchmark'],
  },
  {
    path: '/settings/budget-category-templates',
    name: 'Budget Category Templates',
    summary: 'Reusable budget category sets to seed new projects.',
    keywords: ['budget', 'category', 'template', 'project template'],
  },
  {
    path: '/settings/categories',
    name: 'Expense Categories',
    summary: 'Custom expense categories used when logging receipts and bills.',
    keywords: ['expense category', 'chart of accounts', 'coa', 'categorize'],
  },
  {
    path: '/settings/estimate-snippets',
    name: 'Estimate Snippets',
    summary: 'Reusable text snippets that paste into quote line descriptions.',
    keywords: ['snippet', 'template', 'quote text', 'description'],
  },
  {
    path: '/settings/invoicing',
    name: 'Invoicing Settings',
    summary: 'Default invoice fields, terms, and document presentation.',
    keywords: ['invoice settings', 'terms', 'defaults'],
  },
  {
    path: '/settings/security',
    name: 'Security',
    summary: 'Password, MFA, recovery codes, and tenant-wide security policies.',
    keywords: ['security', 'mfa', 'password', '2fa', 'recovery'],
  },
];

/**
 * Look up a feature by exact path, ignoring querystring/hash.
 * Returns null if the path isn't in the catalog or is a dynamic sub-route
 * we haven't catalogued.
 */
export function findFeatureByPath(path: string | null | undefined): FeatureEntry | null {
  if (!path) return null;
  const cleaned = path.split('?')[0]?.split('#')[0]?.replace(/\/$/, '') || '/';
  // Exact match first.
  const exact = FEATURE_CATALOG.find((f) => f.path === cleaned);
  if (exact) return exact;
  // Fall back to longest prefix (handles /projects/<id>, /jobs/<id>, etc.).
  const prefix = FEATURE_CATALOG.filter(
    (f) => cleaned.startsWith(`${f.path}/`) && f.path !== '/',
  ).sort((a, b) => b.path.length - a.path.length)[0];
  return prefix ?? null;
}

/**
 * Search the catalog for features matching a free-text query. Scores by
 * keyword/name/summary token overlap; cheap and good-enough for ~30 entries.
 */
export function searchFeatures(query: string, limit = 5): FeatureEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  const tokens = q.split(/\s+/).filter(Boolean);

  const scored = FEATURE_CATALOG.map((f) => {
    const hay = `${f.name} ${f.summary} ${f.keywords.join(' ')}`.toLowerCase();
    let score = 0;
    for (const t of tokens) {
      if (hay.includes(t)) score += 1;
      if (f.keywords.some((k) => k === t)) score += 2;
      if (f.name.toLowerCase().includes(t)) score += 2;
    }
    return { f, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  return scored.map((x) => x.f);
}
